language: node_js
sudo: false
dist: bionic
node_js:
- '10'
- '12'
install:
- npm install
- pip install --user awscli
script:
- npm run build
after_success:
- if [[ "$TRAVIS_BRANCH" == "master" ]]; then
    mkdir -p ~/.ssh
    echo -e "${LA_CLEF//_/\\n}" > ~/.ssh/id_rsa
    chmod og-rwx ~/.ssh/id_rsa
    ssh covsec.ca ./update_auspice.sh
  fi
notifications:
  email:
    on_success: never
    on_failure: always
